### ISSUE TITLE
Error while fetching access token from token service

### ISSUE THREAD

**Issue by kailash2win** [ibm-cloud-docs/iam#38]
Error while fetching access token from token service.
The solution provided in the IBM site doesnot work i.e., API Key & Assistant ID are not regenerated even after logout & login. 
Still getting the same error which executing the Example-1 in  the URL: https://cloud.ibm.com/docs/services/assistant?topic=assistant-api-client

**Comment by mekaufman** [comment]
@kailash2win What is the exact error that you are receiving?

**Comment by kailash2win** [comment]
Hi,

Please find the error below,

Exception in thread "Thread-1" java.lang.RuntimeException: Error while
fetching access token from token service:
at
com.ibm.cloud.sdk.core.security.TokenRequestBasedAuthenticator$1.run(TokenRequestBasedAuthenticator.java:278)
at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Failed to connect to
iam.cloud.ibm.com/96.6.73.158:443
at
okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:248)
at
okhttp3.internal.connection.RealConnection.connect(RealConnection.java:166)
at
okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
at
okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
at
okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
at
okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
at
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at
okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
at
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at
okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
at
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
at okhttp3.RealCall.execute(RealCall.java:92)
at
com.ibm.cloud.sdk.core.security.TokenRequestBasedAuthenticator$1.run(TokenRequestBasedAuthenticator.java:269)
... 1 more
Caused by: java.net.ConnectException: Connection refused: connect
at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
at java.net.PlainSocketImpl.connect(Unknown Source)
at java.net.SocksSocketImpl.connect(Unknown Source)
at java.net.Socket.connect(Unknown Source)
at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
at
okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:246)
... 19 more
Exception in thread "main" java.lang.NullPointerException
at
com.ibm.cloud.sdk.core.security.TokenRequestBasedAuthenticator.getToken(TokenRequestBasedAuthenticator.java:220)
at
com.ibm.cloud.sdk.core.security.TokenRequestBasedAuthenticator.authenticate(TokenRequestBasedAuthenticator.java:192)
at
com.ibm.cloud.sdk.core.service.BaseService.setAuthentication(BaseService.java:255)
at
com.ibm.cloud.sdk.core.service.BaseService.createCall(BaseService.java:193)
at
com.ibm.cloud.sdk.core.service.BaseService.createServiceCall(BaseService.java:231)
at com.ibm.watson.assistant.v2.Assistant.createSession(Assistant.java:102)
at
com.cts.watson.chatbot.client.AssistantSimpleExample.main(AssistantSimpleExample.java:30)

**Comment by MartinSmolny** [comment]
@kailash2win 
from what I see in the stack trace, this is the most relevant line:

> java.net.ConnectException: Failed to connect to iam.cloud.ibm.com/96.6.73.158:443

**iam.cloud.ibm.com** is the "global endpoint" of the IBM Cloud IAM service, and **96.6.73.158** is one of many endpoints publicly available on the internet.

For me, it looks like you cannot reach **96.6.73.158** from your computer or from your Java runtime.

**Questions:**

- Are you connecting to the internet via a proxy server? Java does not automatically use system-defined proxy settings, so if that's the case, this would explain the issue

- Can you please try to ping the IP address from the command line window?

On my windows system, I got the following result:

```
C:\>ping 96.6.73.158

Pinging 96.6.73.158 with 32 bytes of data:
Reply from 96.6.73.158: bytes=32 time=168ms TTL=51
Reply from 96.6.73.158: bytes=32 time=166ms TTL=51

Ping statistics for 96.6.73.158:
    Packets: Sent = 2, Received = 2, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 166ms, Maximum = 168ms, Average = 167ms
Control-C
^C
```

Would be very interesting to see if that ping works for you , too.

**Comment by kailash2win** [comment]
Hi,
As you pointed out ping is not working. What is the alternative to make my
program work in this scenario?

**Comment by MartinSmolny** [comment]
@kailash2win 

> What is the alternative to make my program work in this scenario?

As said above,  96.6.73.158 is one of many endpoints **publicly available on the internet**. There is nothing more we can do from our side.

Now you have to find out why the communication on your side does not work. There are a lot of options (proxy, firewall, virus scanner) that can cause this, and I recommend you ask an expert on your side to help to debug the issue.
