### ISSUE TITLE
Odd link(ing)

### ISSUE THREAD

**Issue by jjasghar** [ibm-cloud-docs/iam#42]
```
IBM Cloud Identity and Access Management provides a quick overview of what IAM is in {{site.data.keyword.Bluemix_notm}}, the available features, and links to available CLI and API docs.

IAM concepts outlines the high-level concepts in IAM that can help you understand the different components as you get started.
```
At this location, the two first links both go to the https://cloud.ibm.com/docs/iam?topic=iam-iamoverview page. This seems weird, like they should be one sentence or something not two links right by one another that goes to the same place.

**Comment by mekaufman** [comment]
@jjasghar Thanks for the feedback. I just pushed an update.
