### ISSUE TITLE
"-f" flag is referenced, but no longer appears to be supported for using a file that contains the API key

### ISSUE THREAD

**Issue by joebarrera** [ibm-cloud-docs/iam#47]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
The page has the following line, "Use the -f option to generate an API key file instead of showing the key in the command window:" The problem here is that the "ibmcloud iam api-key-create" command doesn't support "-f", it supports "--file".
2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/iam/federated_id?topic=iam-federated_id#federated_id
3. Do you have a suggestion about how to resolve the issue?
Update the page in the two places where the "-f" flag is used to instead by "--file".

**Comment by mekaufman** [comment]
@joebarrera Thank you so much for your feedback on the documentation. You should see an update by tomorrow morning.
