### ISSUE TITLE
Can't Scan the Bar Code - broken

### ISSUE THREAD

**Issue by jaredeklee13** [ibm-cloud-docs/iam#48]
Did you know you can also submit a pull request to update any IBM Cloud documentation topic by clicking the Edit Topic link on any page? For more information, see Providing a content update with a pull request: https://cloud.ibm.com/docs/overview?topic=overview-feedback#feedback-pr.

1. What are the details of the issue you're experiencing?
"Scan the bar code with your app, or click Can't scan the bar code? to enter a provided key." - This doesn't actually work. It fails to generate a key and instead generates a standard authenticator-app QR code. Failing to scan the QR code leads to a "MFA already enabled" error.

2. Is this issue in reference to a specific page? If so, please provide a link.

3. Do you have a suggestion about how to resolve the issue?
(1) Actually generate a key. (2) Allow account admins to self service reseting user accounts. IBM support took 72 hrs to resolve the issue because they lost the ticket.

**Comment by mekaufman** [comment]
@jaredeklee13 Thank you for your feedback. I'll provide this feedback to the appropriate team.
