### ISSUE TITLE
Example of using the refresh_token is missing

### ISSUE THREAD

**Issue by dprosper** [ibm-cloud-docs/iam#49]
1. What are the details of the issue you're experiencing?
There does not appear to be an example for using the refresh_token

2. Is this issue in reference to a specific page? If so, please provide a link.
https://cloud.ibm.com/docs/iam?topic=iam-iamtoken_from_apikey

3. Do you have a suggestion about how to resolve the issue?
Please add an example of using the refresh_token.

**Comment by MartinSmolny** [comment]
@dprosper 
The page that you are referring to is documenting the API calls that should be used by customers. There is no scenario in which a customer should use the `refresh_token` grant type. 

In the documented API calls, you see that there is no client used at all. This means, IAM is using the client `default` . This client is not allowed to use the grant_type `refresh_token`. 

IBM Cloud Services (internal or 3rd party) can create IAM client ids and have valid use cases for the grant_type `refresh_token`. If you need more information here, please ping me directly. I will point you to appropriate documentation.
